In [1]:
import os
import shutil
import pandas as pd
import numpy as np
import scipy.stats
from scipy import stats

##### provide the rootfolder where summary.tsv, summary_haplotypes.tsv are

In [2]:
## root_folder = '/path/to_your/folder'

if root_folder[-1] == '/':
    root_folder = root_folder[:-1]

In [3]:
summary = pd.read_csv(f'{root_folder}/summary.tsv', sep='\t')
summary.head()

,Haplotype,Contig,Length,NumProdV,Order,LatinName,CommonName,sample,locus,R15_5,...,pi_min,pi_mean,pi_max,sim_95,Simple_repeat,LINE/L1,LTR/ERVL-MaLR,LTR/ERVL,LTR/ERV1,Low_complexity
0,haploid,NW_026622930.1,537463,23,Carnivora,Ursus arctos,brown bear,UrsArc2.0,IGH,0.315551,...,0.919355,94.680438,0.976589,39.130435,0.010522,0.385215,0.009950,0.017369,0.008855,0.010107
1,haploid,NW_026623100.1,180004,16,Carnivora,Ursus arctos,brown bear,UrsArc2.0,IGK,0.000000,...,0.668605,83.082850,0.923567,0.000000,0.016327,0.139230,0.018205,0.028816,0.004961,0.005917
2,haploid,NW_026623030.1,1148887,47,Carnivora,Ursus arctos,brown bear,UrsArc2.0,IGL,0.315658,...,0.608696,86.259732,1.000000,17.021277,0.015775,0.259370,0.008148,0.022050,0.016293,0.003567
3,haploid,NW_026622985.1,139638,8,Carnivora,Ursus arctos,brown bear,UrsArc2.0,TRB,0.000000,...,0.573003,69.344400,0.939799,0.000000,0.021155,0.140807,0.021892,0.014731,0.004075,0.005579
4,primary,SUPER_3,245272,15,Artiodactyla,Balaenoptera acutorostrata,minke whale,mBalAcu1,IGH,0.364493,...,0.606648,87.544460,0.986441,40.000000,0.018225,0.265297,0.015081,0.003372,0.039409,0.001888

### Average Percent Identity VS Tandemness

The average percent identity is higher in IG/TR loci with high HMRC as compared to IG/TR loci with medium and low HMRC.

In [4]:
non_tandem = summary[summary['hmrc']=='low']['pi_mean']
semi_tandem = summary[summary['hmrc']=='medium']['pi_mean']
high_tandem = summary[summary['hmrc']=='high']['pi_mean']

t = stats.kruskal(non_tandem, semi_tandem, high_tandem)
t.pvalue

1.2747937351940374e-15

In [5]:
print(f'Average Mean Percent Identity for low hmrc = {round(np.mean(non_tandem), 1)}')
print(f'Average Mean Percent Identity for medium hmrc = {round(np.mean(semi_tandem), 1)}')
print(f'Average Mean Percent Identity for high hmrc = {round(np.mean(high_tandem), 1)}')

Average Mean Percent Identity for low hmrc = 80.0
Average Mean Percent Identity for medium hmrc = 92.0
Average Mean Percent Identity for high hmrc = 95.1

Moreover, IG/TR loci with high HMRC have a higher percentage of V genes with >95% similarity to another V gene within the same locus (average 61.0%) compared to IG/TR loci with medium (46.9%) and low (17.9%) HMRC.

In [6]:
non_tandem = summary[summary['hmrc']=='low']['sim_95']
semi_tandem = summary[summary['hmrc']=='medium']['sim_95']
high_tandem = summary[summary['hmrc']=='high']['sim_95']

t = stats.kruskal(non_tandem, semi_tandem, high_tandem)
t.pvalue

3.071661140004344e-11

In [7]:
print('percentage of V genes that have at least 95% similarity to another V gene within the same locus for:')
print(f' -low hmrc = {round(np.mean(non_tandem), 1)}')
print(f' -medium hmrc = {round(np.mean(semi_tandem), 1)}')
print(f' -high hmrc = {round(np.mean(high_tandem), 1)}')

percentage of V genes that have at least 95% similarity to another V gene within the same locus for:
 -low hmrc = 17.8
 -medium hmrc = 46.9
 -high hmrc = 61.0

### Repeats

LINE/L1 has the highest coverage, then come LTR/ERVL, simple repeats, LTR/ERVL-MalR, and LTR/ERV1. Tandem IG/TR loci have higher coverage by LINE/L1 and LTR/ERV1 repeats.

In [8]:
type_line = round(np.mean(summary['LINE/L1'])*100, 1)
type_ervl = round(np.mean(summary['LTR/ERVL'])*100, 1)
type_simple = round(np.mean(summary['Simple_repeat'])*100, 1)
type_malr = round(np.mean(summary['LTR/ERVL-MaLR'])*100, 1)
type_erv1 = round(np.mean(summary['LTR/ERV1'])*100, 1)

print(f'Average locus coverage:')
print(f' -LINE/L1 = {type_line}')
print(f' -LTR/ERVL = {type_ervl}')
print(f' -Simple_repeat = {type_simple}')
print(f' -LTR/ERVL-MaLR = {type_malr}')
print(f' -LTR/ERV1 = {type_erv1}')

Average locus coverage:
 -LINE/L1 = 18.8
 -LTR/ERVL = 2.0
 -Simple_repeat = 1.8
 -LTR/ERVL-MaLR = 1.3
 -LTR/ERV1 = 0.9

### Repeats VS Tandemness

In [9]:
print('Tandem IG/TR loci have higher coverage:')

non_tandem = summary[summary['hmrc']=='low']['LINE/L1']
semi_tandem = summary[summary['hmrc']=='medium']['LINE/L1']
high_tandem = summary[summary['hmrc']=='high']['LINE/L1']

t = stats.kruskal(non_tandem, semi_tandem, high_tandem)
print(f' -by LINE/L1: {round(t.pvalue, 2)}')

###

non_tandem = summary[summary['hmrc']=='low']['LTR/ERV1']
semi_tandem = summary[summary['hmrc']=='medium']['LTR/ERV1']
high_tandem = summary[summary['hmrc']=='high']['LTR/ERV1']

t = stats.kruskal(non_tandem, semi_tandem, high_tandem)
print(f' -by LTR/ERV1: {round(t.pvalue, 3)}')

Tandem IG/TR loci have higher coverage:
 -by LINE/L1: 0.01
 -by LTR/ERV1: 0.001

## haplotypes

In [10]:
summary = pd.read_csv(f'{root_folder}/summary_haplotypes.tsv', sep='\t')
summary.head()

,Order,LatinName,CommonName,sample,locus,exp_area,pi_mean,size2,pair12,pairPN,#genes,12%pairs,12%genes,PN%pairs,PN%genes
0,Chiroptera,Myotis yumanensis,Yuma myotis,mMyoYum1.0p2,IGH,57.512928,95.197677,105,74,9,380,70.476190,38.947368,8.571429,4.736842
1,Primates,Lemur catta,Ring-tailed lemur,mLemCat1,IGH,87.049142,97.211936,37,19,1,167,51.351351,22.754491,2.702703,1.197605
2,Carnivora,Mustela nivalis,Least weasel,mMusNiv1,IGH,70.585344,96.609338,42,37,2,112,88.095238,66.071429,4.761905,3.571429
3,Carnivora,Zalophus californianus,California sea lion,mZalCal1,IGH,90.144785,96.695291,9,8,0,26,88.888889,61.538462,0.000000,0.000000
4,Cingulata,Dasypus novemcinctus,nine-banded armadillo,mDasNov1,IGH,88.619505,99.613324,173,172,1,350,99.421965,98.285714,0.578035,0.571429

### Hoplotypes Similarity (IG vs TR)

TR haplotypes are more similar compared to IG haplotypes.

In [11]:
ig = list(summary[summary['locus'].isin(['IGH', 'IGK', 'IGL'])]['exp_area'])
tr = list(summary[summary['locus'].isin(['TRA', 'TRB'])]['exp_area'])

t = stats.kruskal(ig, tr)

print(f'TR haplotypes are more similar compared to IG haplotypes with P={round(t.pvalue, 7)}')

TR haplotypes are more similar compared to IG haplotypes with P=0.0047808

Artiodactyla and Carnivora species have more similar IG locus haplotypes compared to Chiroptera and Rodentia, this similarity persists in TR pairs, however, it is less distinct.

In [12]:
target = summary[summary['Order'].isin(['Carnivora','Chiroptera', 'Artiodactyla', 'Rodentia'])]
target = target[target['locus'].isin(['IGH', 'IGK', 'IGL'])]

blue = list(target[target['Order'].isin(['Artiodactyla', 'Carnivora'])]['exp_area'])
orange = list(target[target['Order'].isin(['Chiroptera', 'Rodentia'])]['exp_area'])
t = stats.kruskal(blue, orange)

print(f'Artiodactyla and Carnivora species have more similar IG locus haplotypes compared to \nChiroptera and Rodentia with P={round(t.pvalue, 9)}.')

Artiodactyla and Carnivora species have more similar IG locus haplotypes compared to
Chiroptera and Rodentia with P=1.329e-06.

In [13]:
target = summary[summary['Order'].isin(['Carnivora','Chiroptera', 'Artiodactyla', 'Rodentia'])]
target = target[target['locus'].isin(['TRA', 'TRB'])]

blue = list(target[target['Order'].isin(['Artiodactyla', 'Carnivora'])]['exp_area'])
orange = list(target[target['Order'].isin(['Chiroptera', 'Rodentia'])]['exp_area'])
t = stats.kruskal(blue, orange)

print(f'Artiodactyla and Carnivora species have more similar TR locus haplotypes compared to \nChiroptera and Rodentia with P={round(t.pvalue, 9)}.')

Artiodactyla and Carnivora species have more similar TR locus haplotypes compared to
Chiroptera and Rodentia with P=0.000781401.

### Average Percent Identity VS Hoplotype Similarity

The computed V gene similarities positively correlate with haplotype similarity values.

In [14]:
ig = summary[summary['locus'].isin(['IGH', 'IGK', 'IGL'])]

haplotypes_similarity = ig['exp_area']
genes_simialrity = ig['pi_mean']

corr_coef, p_value = scipy.stats.pearsonr(haplotypes_similarity, genes_simialrity)
print(f'For IG: correlation coef. = {round(corr_coef, 2)}; P-value = {round(p_value, 20)}')

For IG: correlation coef. = 0.77; P-value = 4.848827219e-11

In [15]:
ig = summary[summary['locus'].isin(['IGH', 'IGK', 'IGL'])]
ig = ig[ig['pi_mean']>85]

haplotypes_similarity = ig['exp_area']
genes_simialrity = ig['pi_mean']

corr_coef, p_value = scipy.stats.pearsonr(haplotypes_similarity, genes_simialrity)
print(f'For IG: correlation coef. = {round(corr_coef, 2)}; P-value = {round(p_value, 20)}')

For IG: correlation coef. = 0.77; P-value = 2.5719534e-10

### Hapltypes Similarity VS % Homologous Pairs

Percentage of homologous pairs positively correlates with haplotype similarity. The percentage of clusters of size 2 where one V gene is productive and another is non-productive and showed that it negatively correlates with haplotype similarity.

In [16]:
ig = summary[summary['locus'].isin(['IGH', 'IGK', 'IGL'])]

haplotypes_similarity = ig['exp_area']
homo_pairs = ig['12%genes']

corr_coef, p_value = scipy.stats.pearsonr(haplotypes_similarity, homo_pairs)
print(f'For IG: correlation coef. = {round(corr_coef, 2)}; P-value = {round(p_value, 20)}')

For IG: correlation coef. = 0.7; P-value = 1.510782423814e-08

In [17]:
ig = summary[summary['locus'].isin(['IGH', 'IGK', 'IGL'])]

haplotypes_similarity = ig['exp_area']
homo_pairs = ig['PN%genes']

corr_coef, p_value = scipy.stats.pearsonr(haplotypes_similarity, homo_pairs)
print(f'For IG: correlation coef. = {round(corr_coef, 2)}; P-value = {round(p_value, 3)}')

For IG: correlation coef. = -0.42; P-value = 0.002